jobs:
  - scene: "default"
    variant: "st"
    iterations: 10
  - scene: "default"
    variant: "mt"
    iterations: 100
  - scene: "test"
    variant: "st"
    iterations: 10
  - scene: "test"
    variant: "mt"
    iterations: 100
