scenes:
  - tag: "cornell"
    name: "Sphere Cornell Box"
    description: "Contains all material types and tests many light phenomenoms"
    max_depth: 5
    width: 640
    height: 480
    filter_type: 0
    cam_angle_x: 0.04258603374866164
    cam_angle_y: 0.0
    cam_dist: 5.5
    focus_x: 0.0
    focus_y: 1.25
    focus_z: 0.0

  - tag: "caustics"
    name: "Caustics"
    description: "Glass spheres, diffuse ground, and colored area lights"
    max_depth: 6
    width: 640
    height: 480
    filter_type: 0
    cam_angle_x: 0.4
    cam_angle_y: 0.0
    cam_dist: 4.0
    focus_x: 0.0
    focus_y: 1.05
    focus_z: 0.0
jobs:
  - scene: "example1"
    variant: "std"
    tag: "cornell"
    iterations: 20

  - scene: "example2"
    variant: "rr"
    tag: "caustics"
    iterations: 5
  
  # - scene: "example3"
  #   variant: "rr"
  #   tag: "caustics"
  #   iterations: 10
  #
  # - scene: "example4"
  #   variant: "rr"
  #   tag: "caustics"
  #   iterations: 10
