name: 'Process Benchmark Data'
description: 'Updates the orphan benchmark branch with new scores'
inputs: 
  bench_version:
    required: true
  modes:
    required: true
    default: 'st mt'
runs:
  using: "composite"
  steps:
    - name: Checkout Benchmark Branch
      uses: actions/checkout@v4
      with:
        ref: benchmarks
        path: data-branch
        fetch-depth: 0

    - name: Setup Python & Dependencies
      shell: bash
      run: |
        python3 -m pip install matplotlib # Added for graph generation

    - name: Integrate Data and Renderings
      shell: bash
      run: |
        mkdir -p data-branch/logs
        mkdir -p data-branch/renderings
        
        # 1. Archive the RAW log
        cp tests/img/exr/zig_render/zig_render_log.txt data-branch/latest_raw_log.txt
        cp tests/img/exr/zig_render/zig_render_log.txt data-branch/logs/${{ inputs.bench_version }}.log

        # 2. Generate the Static Convergence Graph
        python3 scripts/generate_plots.py data-branch/latest_raw_log.txt data-branch/renderings/convergence.png

        # 3. Handle Preview Images
        for mode in ${{ inputs.modes }}; do
          if [ -f "preview-$mode.png" ]; then
            cp "preview-$mode.png" "data-branch/renderings/latest-$mode.png"
            cp "preview-$mode.png" "data-branch/renderings/${{ inputs.bench_version }}-$mode.png"
          fi
        done

    - name: Update CSV and Dashboard
      shell: bash
      run: |
        python3 scripts/update_benchmark.py rmse_results.json data-branch/history.csv
        # Note: We update generate_dashboard.py to point to the new convergence.png
        python3 scripts/generate_dashboard.py data-branch/history.csv data-branch/README.md data-branch/latest_raw_log.txt    - name: Commit and Push
      shell: bash
      working-directory: data-branch
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Benchmark: ${{ inputs.bench_version }}" || echo "No changes"
        git push origin HEAD:benchmarks
