name: 'Process Benchmark Data'
description: 'Updates the orphan benchmark branch with new scores and plots'

inputs: 
  bench_version:
    description: 'The version/build string for the current run'
    required: true
  modes:
    description: 'The rendering modes to process (e.g., st mt)'
    required: true
    default: 'st mt'

runs:
  using: "composite"
  steps:
    - name: Checkout Benchmark Branch
      uses: actions/checkout@v4
      with:
        ref: benchmarks
        path: data-branch
        fetch-depth: 0

    - name: Setup Python & Dependencies
      shell: bash
      run: |
        python3 -m pip install matplotlib

    - name: Integrate Data and Renderings
      shell: bash
      run: |
        mkdir -p data-branch/logs
        mkdir -p data-branch/renderings
        
        # 1. Archive the RAW log
        cp -f tests/img/exr/zig_render/zig_render_log.txt data-branch/latest_raw_log.txt
        cp -f tests/img/exr/zig_render/zig_render_log.txt data-branch/logs/${{ inputs.bench_version }}.log

        # 2. Update History CSV (needs to happen before generating plots)
        # We must update the CSV *before* generating plots so the trend graph includes this run.
        python3 scripts/update_benchmark.py rmse_results.json data-branch/history.csv

        # 3. Generate BOTH Plots (Log, CSV, OutputDir)
        # Now data-branch/history.csv contains the latest data
        python3 scripts/generate_plots.py data-branch/latest_raw_log.txt data-branch/history.csv data-branch/renderings/ 30

        # 4. Handle Preview Images
        for mode in ${{ inputs.modes }}; do
          if [ -f "preview-$mode.png" ]; then
            cp "preview-$mode.png" "data-branch/renderings/latest-$mode.png"
            cp "preview-$mode.png" "data-branch/renderings/${{ inputs.bench_version }}-$mode.png"
            cp "preview-$mode.png" "data-branch/renderings/latest.png"
          fi
        done

        # 4. Copy Reference Image to a fixed path
        if [ -f "preview-reference.png" ]; then
          cp "preview-reference.png" "data-branch/renderings/reference.png"
        fi

    - name: Update Dashboard
      shell: bash
      run: |
        # Update Benchmark removed from here as it is now done in the previous step
        python3 scripts/generate_dashboard.py data-branch/history.csv data-branch/README.md data-branch/latest_raw_log.txt

    - name: Commit and Push
      shell: bash
      working-directory: data-branch
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add .
        # Using --allow-empty or || true to prevent pipeline failure if nothing changed
        git commit -m "Benchmark: ${{ inputs.bench_version }}" || echo "No changes to commit"
        git push origin HEAD:benchmarks
