name: 'Process Benchmark Data'
description: 'Updates the orphan benchmark branch with new scores'
inputs: 
  bench_version:
    required: true
  modes:
    required: true
    default: 'st mt'
runs:
  using: "composite"
  steps:
    - name: Checkout Benchmark Branch
      uses: actions/checkout@v4
      with:
        ref: benchmarks
        path: data-branch
        fetch-depth: 0

    - name: Integrate Data and Renderings
      shell: bash
      run: |
        mkdir -p data-branch/logs
        mkdir -p data-branch/renderings

        # Archive the RAW log for convergence parsing later
        # We MUST move this into data-branch so scripts can see it
        cp tests/img/exr/zig_render/zig_render_log.txt data-branch/latest_raw_log.txt
        cp tests/img/exr/zig_render/zig_render_log.txt data-branch/logs/${{ inputs.bench_version }}.log

        # Handle images
        for mode in ${{ inputs.modes }}; do
          if [ -f "preview-$mode.png" ]; then
            cp "preview-$mode.png" "data-branch/renderings/latest-$mode.png"
            cp "preview-$mode.png" "data-branch/renderings/${{ inputs.bench_version }}-$mode.png"
          fi
        done

        # Fallback image
        LAST_MODE=$(echo "${{ inputs.modes }}" | awk '{print $NF}')
        cp "preview-$LAST_MODE.png" "data-branch/renderings/latest.png"

    - name: Update CSV and Dashboard
      shell: bash
      run: |
          if [ ! -f "data-branch/latest_raw_log.txt" ]; then
          echo "ERROR: Log file missing!"
          exit 1
          fi
        # Use the JSON we created in the main workflow
        python3 scripts/update_benchmark.py rmse_results.json data-branch/history.csv
        
        # Override the hardcoded path in dashboard script by passing it
        # (Assuming you update generate_dashboard.py to accept this path)
        python3 scripts/generate_dashboard.py data-branch/history.csv data-branch/README.md data-branch/latest_raw_log.txt

    - name: Commit and Push
      shell: bash
      working-directory: data-branch
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Benchmark: ${{ inputs.bench_version }}" || echo "No changes"
        git push origin HEAD:benchmarks
