name: 'EXR Directory to PNG Conversion'
description: 'Converts all EXR files in a directory to PNG previews'

inputs:
  input_dir:
    description: 'Directory containing .exr files'
    required: true
    default: 'tests/img/exr/zig_render/'
  output_dir:
    description: 'Directory where .png files should be saved'
    required: true
    default: 'tests/img/exr/previews/'
  filename:
    description: 'Filename of the output png file without file suffix'
    required: false
    default: ''
  
runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Conversion Dependencies
      shell: bash
      run: pip install mitsuba numpy Pillow

    - name: Convert EXRs to PNGs
      shell: bash
      # Pass the directories to the script
      run: python3 scripts/exr_to_png.py "${{ inputs.input_dir }}" "${{ inputs.output_dir }} "${{ inputs.filename }}
