name: 'EXR to PNG Conversion'
description: 'Sets up Python and converts the rendered EXR to a PNG preview'

inputs:
  input_path:
    description: 'Path to the source .exr file'
    required: true
    default: 'tests/img/exr/zig_render/render_zig.exr'
  output_path:
    description: 'Path where the .png should be saved'
    required: true
    default: 'preview.png'

runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Conversion Dependencies
      shell: bash
      run: pip install mitsuba numpy Pillow

    - name: Convert EXR to PNG
      shell: bash
      # We pass the inputs directly to the python script as arguments
      run: python3 exr_to_png.py "${{ inputs.input_path }}" "${{ inputs.output_path }}"
